### ISSUE TITLE
Create documentation and strong types, similar to signify-browser-extension

### ISSUE THREAD

**Issue by 2byrds** [WebOfTrust/polaris-web#10]
@lenkan and others will use polaris-web without knowledge of the signify-browser-extension and currently that's where the interface and methods are documented.
Improve this repo to 'stand-alone' with documentation that guides and extension implementor to be to quickly understand the inputs/outputs.
Also consider a future issue to address versioning as we move forward (potentially create additional issues).

**Comment by lenkan** [comment]
One additional thing that would be good to include is the error handling. How does the content script indicate to polaris-web that a particular request has failed?

**Comment by 2byrds** [comment]
> One additional thing that would be good to include is the error handling. How does the content script indicate to polaris-web that a particular request has failed?

@HunnySajid per @lenkan question can you respond here and let us know if this can be closed?

**Comment by lenkan** [comment]
There is a mechanism for error handling added, see for example this test here: https://github.com/WebOfTrust/polaris-web/blob/bcb5283c42fa4f8e4b837b04a5962a3da97fc8d4/src/client.test.ts#L145-L158

**Comment by lenkan** [comment]
Also, the example app provides sufficient standalone documentation in my opinion.
