### ISSUE TITLE
Implementation suggestion for Nord Vlei Extension

### ISSUE THREAD

**Issue by HunnySajid** [WebOfTrust/polaris-web#17]
In polaris-web, there are three different methods with a slightly different implementation as per the use cases of signify-polaris-web.
Namely:
- `authorize`
- `authorizeAid`
- `authorizeCred`

**Signify Extension**

If `authorize` call is made user can select both credential or aid
If `authorizeAid` call is made user can only select aid
If `authorizeCred` call is made user can only select a credential

<img width="656" alt="Screenshot 2024-08-06 at 7 54 42 PM" src="https://github.com/user-attachments/assets/3c6b81e6-f08d-48a6-b295-754b7146bf2e">
<img width="656" alt="Screenshot 2024-08-06 at 7 54 29 PM" src="https://github.com/user-attachments/assets/82e7401d-7a63-42b2-b631-fd34b29850ce">

However, this behavior is a bit different in Nord Vlei. NordVlei extension only listens to `authorize` method call and based on that displays a `list of credentials` to be selected.

**State of NordVlei extension when `authorize` call is made from polaris-web**
<img width="379" alt="Screenshot 2024-08-06 at 7 53 56 PM" src="https://github.com/user-attachments/assets/d3cf8245-1200-4b01-ab9b-301423789dab">

We want to make [Reg Pilot Web APP](https://github.com/GLEIF-IT/reg-pilot-webapp) compatible with both NordVlei and Signify Extension. 
If we use `authorize`: In Signify Extension, it would allow user to pick any of Credential or AID, we dont want that.
If we use `authorizeCred`: it is not implemented in NordVlei and it would not be listened.

**Suggestion:** 
Our suggestion is to replace `authorize` method in NordVlei with `authorizeCred`. That way it would be compatible for both of the extensions.

@2byrds

**Comment by 2byrds** [comment]
@HunnySajid thank you for the details. @lenkan and @daviddm lets discuss when you return.

**Comment by lenkan** [comment]
Thanks for the detailed description @HunnySajid ! We have added support for authorizeCred in our extension now, we just need to wait for approval before publishing the updated extension.

**Comment by 2byrds** [comment]
> Thanks for the detailed description @HunnySajid ! We have added support for authorizeCred in our extension now, we just need to wait for approval before publishing the updated extension.

That's great, go team!

**Comment by lenkan** [comment]
It is now published in version 0.0.5 of the extension in the chrome store.

**Comment by HunnySajid** [comment]
> It is now published in version 0.0.5 of the extension in the chrome store.

much appreciated 👏
