### ISSUE TITLE
Proposal: github actions workflow to run on PRs

### ISSUE THREAD

**Issue by lenkan** [WebOfTrust/polaris-web#23]
Suggested checks:

- Prettier format check
- Eslint linting
- Typescript typecheck
- Vitest test run

**Comment by 2byrds** [comment]
@HunnySajid can you add this. It should be similar to the signify-ts checks, see https://github.com/WebOfTrust/signify-ts/blob/main/.github/workflows/main.yml

**Comment by HunnySajid** [comment]
> @HunnySajid can you add this. It should be similar to the signify-ts checks, see https://github.com/WebOfTrust/signify-ts/blob/main/.github/workflows/main.yml

sure, can you please assign it to me?

**Comment by 2byrds** [comment]
Per https://github.com/WebOfTrust/polaris-web/issues/20 the workflow can will publish a dev tag to npm on each PR merge.
