### ISSUE TITLE
Remove wildcard from Postmessage

### ISSUE THREAD

**Issue by HunnySajid** [WebOfTrust/polaris-web#4]
Currently we are using wildcard '*' while communicating with postMessage. It is not correct as it broadcasts messages to all.
We need to fix it so that communication can only be between out content script and webpage.

Relevant links:
https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage#using_window.postmessage_in_extensions_non-standard

Linked Issue on signify-extension:
https://github.com/WebOfTrust/signify-browser-extension/issues/159

**Comment by lenkan** [comment]
This is now implemented as an option:

https://github.com/WebOfTrust/polaris-web/blob/bcb5283c42fa4f8e4b837b04a5962a3da97fc8d4/src/client.ts#L143
https://github.com/WebOfTrust/polaris-web/blob/bcb5283c42fa4f8e4b837b04a5962a3da97fc8d4/src/client.ts#L337

Is that sufficient to be able to close this? The default behavior is that the target origin is "/", which means same origin according to [spec](https://html.spec.whatwg.org/dev/web-messaging.html#posting-messages).

**Comment by HunnySajid** [comment]
@lenkan thanks for looking into it, can be closed now.
